import initSubtleScroll from "./modules/subtle-scroll.js";
import initScrollAnimation from "./modules/scroll-anima.js";
import initTabNav from "./modules/tabnav.js";
import initAccordion from "./modules/accordion-list.js";
import initModal from "./modules/modal.js";
import initTooltip from "./modules/tooltip.js";
import initDropdownMenu from "./modules/dropdown-menu.js";
import initMenuMobile from "./modules/menu-mobile.js";
import initBusinessHours from "./modules/business-hours.js";
import initFetchAnimals from "./modules/fetch-animals.js";

initSubtleScroll();
initScrollAnimation();
initTabNav();
initAccordion();
initModal();
initTooltip();
initDropdownMenu();
initMenuMobile();
initBusinessHours();
initFetchAnimals();
